version: '3.8'

services:
  linguly-core:
    build: .
    container_name: linguly-core
    networks:
      - coolify
    environment:
      - BASIC_MODEL_URL=${BASIC_MODEL_URL}
      - MONGODB_MAIN_URL=${MONGODB_MAIN_URL}
      - JWT_SECRET=${JWT_SECRET}

networks:
  coolify:
    external: true
