@base_url = http://localhost:3001
### Get all agents
GET {{base_url}}/agents
Content-Type: application/json

###

@agentId = 1_dictionary
### Send a message to an agent
POST {{base_url}}/agent/{{agentId}}/chat
Content-Type: application/json

{
    "content": "Hello, agent!"
}