@base_url = http://localhost:3001
### Get all agents
GET {{base_url}}/agents
Content-Type: application/json

### Agents

@agentId = 1_dictionary
### Send a message to an agent
POST {{base_url}}/agent/{{agentId}}/chat
Content-Type: application/json

{
    "content": "Hello, agent!"
}


### User Authentication

### Login as a user
POST {{base_url}}/user/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test123"
}

### Sign up a new user
POST {{base_url}}/user/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "tes6aaa23",
    "name": "Test User"
}