connections:
  - name: main_db
    url_env_var: MONGODB_MAIN_URL
    type: mongodb

databases:
  - name: user
    connection: main_db
    type: mongodb
    collections:
      - user_auth
  - name: shared_context
    connection: main_db
    type: mongodb
    collections:
      - users
      - goals
      - learning_phrases